### ISSUE TITLE
Resizable

### ISSUE THREAD

**Issue by Smilko** [htl-leonding/2016_3CHIF_hand-in-hand#10]
Elemente werden nicht mitgezogen.

**Comment by SakalAndrej** [comment]
Es funktioniert jetzt etwas besser ist aber auch noch nicht 100%

**Comment by Smilko** [comment]
Resizable-Eigenschaft wurde angepasst.

**Comment by SakalAndrej** [comment]
Hast du das jetzt zu 100% geschafft das alle Elemente mitwachsen?
