### ISSUE TITLE
PhotoViewer - Buttonfunctionality

### ISSUE THREAD

**Issue by Smilko** [htl-leonding/2016_3CHIF_hand-in-hand#14]
Buttons react when pressing on gui:
-Rotate
-Left
-Right

**Comment by SakalAndrej** [comment]
Sollen die Fotos direkt vom angeschlossenem USB angezeigt werden oder werden die Fotos immer in einen bestimmten Ordner auf dem Raspberry Pi draufgeladen. 

Im Fall Nr.: 1 würde ich dann den Directory Watcher verwenden.
Im Fall Nr.: Werden einfach immer auf dem USB vorhandenen Fotos angezeigt

Was ist die bessere Variante?

**Comment by SakalAndrej** [comment]
Die Bilder werden jetzt zuerst einmal in der ersten Version von einem fixen Ordner gelesen und in eine Liste die max 25 Bilder zulässt gespeichert. Diese werden in einer ImageView angezeigt. Man kann auch schon zwischen den Bildern hin und wechseln. Falls es passiert das man beim letzten Bild ankommt dann wird bei einer weiteren betätigung der "Bild wechseln" Taste dann einfach beim ersten Bild wieder angefangen. (Erstes Bild zum letzten, Letztes zum ersten, Loop)

**Comment by SakalAndrej** [comment]
The PhotoViewer is finished!
