### ISSUE TITLE
Testing programms on the raspberry pi

### ISSUE THREAD

**Issue by SakalAndrej** [htl-leonding/2016_3CHIF_hand-in-hand#20]
We exported today all of our jars and now we have to look if they are working on the raspberry pi.

**Comment by SakalAndrej** [comment]
Trotz Shade-Plugin bekommen wir auf dem Raspberry pi die Fehlermeldung ("Can't find or load Main Class ....")

**Comment by SakalAndrej** [comment]
Ich habe herausgefunden das wir unsere Programme nicht ausführen können da der Raspberry Pi JavaFx Applications nicht ausführen kann da JDK und JRE fehlen nachdem ich heute seit fast 4h versuche alle nötigen packages zu installieren hat alles nichts geholfen.

**Comment by htl-leonding** [comment]
Schaut Euch das an. Das verwenden wir
https://blog.codecentric.de/2015/09/kaffee-und-kuchen-projekte-mit-java-embedded-8-auf-dem-raspberry-pi/
http://gluonhq.com/gluon-supports-javafx-embedded-binary-builds-now-available/

mfg
