### ISSUE TITLE
Directory Chooser

### ISSUE THREAD

**Issue by SakalAndrej** [htl-leonding/2016_3CHIF_hand-in-hand#24]
Wir haben ja jetzt bei unseren Programmen immer einen Directory Chooser (Picture Viewer und Music-Player) jedoch war glaube ich geplant das von einem absoluten Pfad die Bilder bzw Lieder gesucht werden sollen?

@Smilko machen wir einen absoluten Pfad einfach als Standard-Ordner wenn das Programm startet und dann kann der Benutzer aber trotzdem einen anderen Ordner aussuchen? :computer:

**Comment by Smilko** [comment]
Eine gute Idee wäre es beides zu verwenden, finde ich. Falls es noch
möglich ist, bitte implementieren, sonst liegt unser Focus auf die
Fehlerfreiheit der Programme.

2016-06-13 14:02 GMT+02:00 Sakal Andrej notifications@github.com:

**Comment by SakalAndrej** [comment]
Directory Chooser wurde bei dem PictureViewer ebenfalls implementiert weiters würde ich das durchsuchen der Unterordner noch als Feature implementieren.

Zur Fehlerfreiheit und lauffähigkeit unserer Programme habe ich einen neuen Issue eröffnet!
