### ISSUE TITLE
Bildbetrachter in Python

### ISSUE THREAD

**Issue by htl-leonding** [htl-leonding/2016_3CHIF_hand-in-hand#25]
Hallo!
Nachdem JavaFX nicht optimal ist, gibt es genau 2 Möglichkeiten: HTML/JS/CSS oder Python
Wir werden zunächst Python implementieren. Dazu verwenden wir den Bildbetrachter **feh**
https://wiki.ubuntuusers.de/Feh/
Das dazugehörige Tutorial gibt's hier:
http://www.instructables.com/id/Easy-Raspberry-Pi-Based-ScreensaverSlideshow-for-E/?ALLSTEPS

Das ganze zu implementieren sollte nicht länger als 30min dauern. Komme am Montag zu euch und seh mir das fertige Ding an. ;-)

Nachteil des Ganzen: Videos funktionieren nicht

Weitere Quellen:
https://ufie.de/raspberry-pi-als-slideshow-kiosk-dss-mit-fernwartung/
http://www.jonathansblog.net/raspberry-pi-powered-presentation-display-foyer-screen
http://www.rowlandtechnology.com/projects/2015/02/13/easy-raspberry-pi-based-screensaverslideshow-for-exhibitions/
https://pimylifeup.com/raspberry-pi-photo-frame/

Weitere Bildbetrachter:
http://www.nongnu.org/fbi-improved/
http://www.binaryemotions.com/digital-signage/raspberry-slideshow/

**Comment by htl-leonding** [comment]
# Bildbetrachter für HTML / JS / CSS
1. http://wowslider.com/
2. http://www.rhinoslider.com/
3. https://daveismyname.com/creating-an-image-gallery-from-a-folder-of-images-automatically-bp

**Comment by SakalAndrej** [comment]
Vielen Dank für die ausführliche Erklärung der 2 Möglichkeiten.

Da wir den Raspberry Pi übers Wochenede in der Schule ließen habe ich mir schon die benötigten Sachen vorbereitet. Und werde dann morgen etwas früher da sein um den Bildbetrachter zu implementieren.

**Comment by htl-leonding** [comment]
Ist nicht ganz optimal, da keine Videos abgespielt werden, aber egal 
(einstweilen).

Am 19/06/16 um 20:26 schrieb Sakal Andrej:

> Vielen Dank für die ausführliche Erklärung der 2 Möglichkeiten.
> 
> Da wir den Raspberry Pi übers Wochenede in der Schule ließen habe ich 
> mir schon die benötigten Sachen vorbereitet. Und werde dann morgen 
> etwas früher da sein um den Bildbetrachter zu implementieren.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub 
> https://github.com/htl-leonding/2016_3CHIF_hand-in-hand/issues/25#issuecomment-227012490, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AOJadgHNWw6VPK7dTVbhGQ5AoG-zJChpks5qNYnjgaJpZM4I5Mtc.

## 

Mit freundlichen Grüßen
Thomas Stütz

HTL Leonding
Limesstraße 12-14
4060 Leonding

**Comment by SakalAndrej** [comment]
Ich bin fertig mit der Implementierung Sie können sich das jetzt gerne ansehen @htl-leonding .

**Comment by SakalAndrej** [comment]
Ich habe jetzt nach einem Videoplayer für den Raspberry gesucht und habe den bereits vorinstallierten omxplayer ausprobiert dieser spielt erfolgreich Mp4 Formate ab. 

Link: **http://elinux.org/Omxplayer#Streaming**

Es wären auch folgende key shortcuts die wir mit unseren 3 Tasten verwenden könnten.
space - pause/resume
left arrow - seek -30 seconds
right arrow - seek +30 seconds

**Comment by htl-leonding** [comment]
Auch wenn ich Gefahr laufe, dass ich Euch nerve, aber ich hätte noch 
eine tolle und wahrscheinlich beste Lösung.
Wir generieren die HTML-Seiten mit Java und geben Sie auf einem 
minimalistischen Server aus.
Damit haben wir die volle Kontrolle über alles, können die bisherige 
Java-Anwendung verwenden und zur Ausgabe gewöhnliches HTML5

Nähere Infos folgen

mfg
Stütz

Am 19/06/16 um 20:26 schrieb Sakal Andrej:

> Vielen Dank für die ausführliche Erklärung der 2 Möglichkeiten.
> 
> Da wir den Raspberry Pi übers Wochenede in der Schule ließen habe ich 
> mir schon die benötigten Sachen vorbereitet. Und werde dann morgen 
> etwas früher da sein um den Bildbetrachter zu implementieren.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub 
> https://github.com/htl-leonding/2016_3CHIF_hand-in-hand/issues/25#issuecomment-227012490, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AOJadgHNWw6VPK7dTVbhGQ5AoG-zJChpks5qNYnjgaJpZM4I5Mtc.

## 

Mit freundlichen Grüßen
Thomas Stütz

HTL Leonding
Limesstraße 12-14
4060 Leonding

**Comment by htl-leonding** [comment]
Hallo!
Habe einen Java-Server gefunden, der ziemlich klein und einfach zu bedienen ist.
Ihr könntet nun (vergleichbar mit String msg) die HTML-Seite zusammenbauen und zurückgeben.
In dieser HTML-Seite könnte man die vorher in Java ausgelesenen Bilder des Verzeichnisses hartcoden.
Die Keystrokes müssten wohl mit JS oder durch Verwendung einer geeigneten Gallery behandelt werden. 

[NanoHttpd.zip](https://github.com/htl-leonding/2016_3CHIF_hand-in-hand/files/323302/NanoHttpd.zip)

**Comment by SakalAndrej** [comment]
Vielen Dank für Ihren Zeitaufwand.

Ich versuche jetzt zuerst einmal herauszufinden wie das mit dem erstellen der HTML-Seite funktioniert. 

Die HTML-Seite soll unser Hand in Hand Programm darstellen damit dann die Tasten zugewiesen werden können. Und nachdem die Tasten zugewiesen wurden soll dann der Benutzer in der HTML-Seite Bilder/Videos ansehen können usw. Habe ich die Aufgabenstellung richtig verstanden?

@gionescu97 wenn du möchtest kannst du einen geeigneten GalleryViewer finden oder halt selber mit JavaScript zusammenbauen.

**Comment by SakalAndrej** [comment]
Fertig!
