### ISSUE TITLE
Pictures for view

### ISSUE THREAD

**Issue by SakalAndrej** [htl-leonding/2016_3CHIF_hand-in-hand#5]
I am finished with the new view, just some functions are not implemented yet like the list view (should show the functions of the buttons). 

I also make a little "about" but I need Pictures of @Smilko @gionescu97 so i can insert them too. 
I also have to work on the resizability a little bit.

Verbesserungsvorschläge?

**Comment by Smilko** [comment]
Najo, i hob des heit osprobiert und des funkt bei Mia iwi ned. Und loss mi
die email nuamoe moagn lesen bitte, i bin jetzt zu müde, sorry.
Ps:Öl
Am 19.04.2016 23:00 schrieb "Sakal Andrej" <notifications@github.com>:

**Comment by SakalAndrej** [comment]
@gionescu97 I need the pictures?

**Comment by Smilko** [comment]
Pictures added to project
