### ISSUE TITLE
ListView

### ISSUE THREAD

**Issue by SakalAndrej** [htl-leonding/2016_3CHIF_hand-in-hand#6]
Ich habe jetzt die View komplett fertig überarbeitet die ListView ist auch schon drinnen und es werden am Anfang 3 Buttons geladen die "not assigned", @Smilko kannst du mir sagen was für Namen die Buttons haben wenn Sie reinkommen? 

Dann müssen wir uns noch ausmachen welcher Key-Name immer diese Funktion hat damit ich das auch noch implementieren kann.

@gionescu97 könntest du machen das im Controller beim Initialize 3 Buttons reingeladen werden über eine .txt wo schon die Standard-Buttons zugewiesen sind oder wir lassen sie "not assigned" aber trotzdem über eine txt damit wirs nicht im Controller machen?

Der Hyperlink funktioniert auch wieder.

**Comment by Smilko** [comment]
Vom Arduino kommt "key0" bis "key8". Die Buttonnamen kann man auf Left,
Space und Right lassen

Am 20. April 2016 um 22:05 schrieb Sakal Andrej notifications@github.com:

**Comment by Smilko** [comment]
View fertig..
