### ISSUE TITLE
3 Taster

### ISSUE THREAD

**Issue by Smilko** [htl-leonding/2016_3CHIF_hand-in-hand#8]
3 Taster bauen:
- 3 x Scharnierl
- 6 x Platte(Bevorzugt mit Holz|10cm x 15cm x ~1cm)
- 6 x Feder
- 1 Rolle Nähfaden
- 12 x "Schraube mit Loch"
- 1 Packung Schrauben
- 3 x Blech
- Schleifpapier

**Comment by SakalAndrej** [comment]
Habe heute beim Bauhaus folgende Sachen gekauft.

```
3 x Scharniere 
6 x Platte (Fichtenholz, 15 x 10 x 1,8)
1 Packung kleine Ringschrauben 20stk
1 Packung mittlere Ringschrauben 20stk
1 Packung kleine Schrauben zum befestigen der Scharniere 
1 Feines Schleifpapier K240
1 Gröberes - . - K180
```
